name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build Go App
        run: |
          go mod tidy
          go build -o main .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA::7}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME
